### PR TITLE
Fix Clang 8

### PR DESCRIPTION
**Pull request by uilianries**
Fix due issue https://github.com/conan-io/conan-docker-tools/pull/112#issuecomment-486361349

### CODE REVIEW

**Comment by Croydon** [comment]
I'm not understanding why this is needed currently. Could you please explain?

Also I would prefer to add new test cases instead of modifying the current ones to test new workarounds

**Comment by uilianries** [comment]
> I'm not understanding why this is needed currently. Could you please explain?

The docker image for clang 8 is partial working when cross-building.

As I commented [here](hhttps://bugs.launchpad.net/ubuntu/+source/llvm-defaults/+bug/1819768). There is a bug involving llvm packages for Ubuntu Disco. Unfortunately, I don't when they will send a new patch. 

The best way to avoid possible errors during construction is by using conanio/clang8-x86

> Also I would prefer to add new test cases instead of modifying the current ones to test new workarounds

I agree, but such test should be executed by conan-docker-tools. That project should be able to detect any limitation from those images.

**Comment by SSE4** [comment]
@Croydon I am tentative, should we merge this one or fix containers instead?

**Comment by Croydon** [comment]
This script would change all new  Clang 8 jobs to use 32bit  docker images, I think that is pretty odd on its own.

How often is this bug causing problems and is it worth updating all Clang 8 images usages with this script or would it be fine to do it manually in this problematic cases until the image is fixed?

**Comment by SSE4** [comment]
I vote for fixing images instead. in the worst case, we may build clang from source or provide our own ppa for a while, but it's better to fix it upstream.

**Comment by Croydon** [comment]
Another note: We can apply this workaround automatically, but we can not undo it automatically, as sometimes it is necessary to use a 32bit container.

If @SSE4 would prefer other solutions as well I think we should close this

**Review by Croydon — CHANGES_REQUESTED** [review]
We should look for a better solution and in the meantime we can apply this workaround manually, if necessary

**Comment by uilianries** [comment]
> I vote for fixing images instead. in the worst case, we may build clang from source or provide our own ppa for a while, but it's better to fix it upstream.

Me too, but again, it's a upstream problem and we can't fix it. I'm good leaving it as it is, but probably we will see clang8 falling for some packages when building x86

**Pull request closed without merging**
