### PR TITLE
Remove shebang + add coding header

### PR DESCRIPTION
**Pull request by madebr**
Also apply this to `test_package/conanfile.py`

### CODE REVIEW

**Review by Croydon — CHANGES_REQUESTED** [review]
* this encoding header is just for some editors, right? what was it? vim? instead of adding meta data for specific editors I would rather remove it from the templates and ignore it in bincrafters-conventions
  * the hashbang is not hurting anyone and has zero effects, also already removed from the templates, I'm not sure if this is worth adding

**Comment by madebr** [comment]
- The shebang is superfluous. A conanfile is not executable.
- The encoding header is a tip for python what encoding the file is in: https://www.python.org/dev/peps/pep-0263/

**Comment by Croydon** [comment]
> The shebang is superfluous

Yes, but completely harmless. It's not needed, read or manipulated by anything at all, so I would prefer to keep this tool smaller instead of adding this. If we start to add any single manipulation we apply to the templates to this tool it will explode in size and complexity 

> The encoding header is a tip for python what encoding the file is in: https://www.python.org/dev/peps/pep-0263/

> The default encoding for Python source code is UTF-8

https://docs.python.org/3/howto/unicode.html

I believe that this encoding header is only relevant for Python 2 and also only if you actually use unicode symbols which aren't also ASCII. Since Python 2 is pretty soon dead and Conan already deprecated support, I don't see why we should care about it.

**Comment by madebr** [comment]
Wouldn't it be nice that all conanfiles have the same header?

**Comment by SSE4** [comment]
@uilianries @madebr @Croydon should we merge or close this one?

**Review by uilianries — APPROVED** [review]

**Comment by uilianries** [comment]
almost all our recipes are using `coding`. I see no problem keeping. I agree with Croydon it's not required for python 3, but I would prefer maintaining a standard.

**Comment by madebr** [comment]
An alternative would be to remove the encoding header since python2 will be EOL'ed by the end of this year.

**Comment by Croydon** [comment]
I was planning to suggest the removal in the templates repository, but life and everything....

**Comment by uilianries** [comment]
> An alternative would be to remove the encoding header since python2 will be EOL'ed by the end of this year.

> I was planning to suggest the removal in the templates repository, but life and everything....

Thinking again, python 2 is almost retired, so I agree with @Croydon

**Comment by madebr** [comment]
What about this: detect presence of coding header.
- If it is utf8, then remove it.
- If something else: keep it.

**Comment by uilianries** [comment]
> What about this: detect presence of coding header.
> 
>     * If it is utf8, then remove it.
> 
>     * If something else: keep it.

I agree removing utf8

What about generating a warning? Usually we don't use them, so if a recipe needs a header it's because something need attention.

**Comment by Croydon** [comment]
To be honest, I fear that stuff like this might end in over-engineering, that's why I'm not a huge fan of it. After all, we have small changes in the templates constantly, but many aren't important enough to be required to get automatically applied in existing recipes, in my opinion. Applying all of them automatically might be overkill without any real benefit

**Comment by uilianries** [comment]
What about doing it by demand? I think this change is not important to be applied immediately, but it can be added to entire bincrafters conventions.

**Comment by SSE4** [comment]
hi @madebr @uilianries @Croydon 
I don't think it's safe to remove encoding header going forward, because it leads to weird errors:
```
RROR: Error loading conanfile at '/Users/sse4/.conan/data/bzip2/1.0.8/conan/stable/export/conanfile.py': Unable to load conanfile in /Users/sse4/.conan/data/bzip2/1.0.8/conan/stable/export/conanfile.py
  File "/Users/sse4/.conan/data/bzip2/1.0.8/conan/stable/export/conanfile.py", line 13
SyntaxError: Non-ASCII character '\xe2' in file /Users/sse4/.conan/data/bzip2/1.0.8/conan/stable/export/conanfile.py on line 13, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by Croydon** [comment]
@SSE4 Where is this error happening? Is it assuming Python 3 per default?

**Comment by SSE4** [comment]
@Croydon on OSX, python 2.7.16

**Comment by uilianries** [comment]
The error occurred because it is python2, not python3.

I remember a similar event when ctre didn't work, because the author name contains non-ascii characters: 

https://github.com/hanickadot/compile-time-regular-expressions/blob/master/conanfile.py#L11

**Review by Croydon — CHANGES_REQUESTED** [review]
We are not adding these headers to new recipes anymore.

I still don't like to blow up this tool with too many detail updates.
Since this might make problem with existing recipes with Python 2, I would say that if we are going to merge this we should wait till we are closer to the end of the year when Python 2 is finally end-of-life.

When @SSE4 or @uilianries thinks at the end of the year that having these updates in the tool is a good idea then it will be fine with me

**Comment by Croydon** [comment]
The situation changed because of the CCI.

When we want to get rid of those meta lines then it's pointless to wait longer, when we mass-transferring recipes to CCI.

Meta lines are now getting removed via 1b37c05431385fb4012ad0ff3a6aa98dd14c96f8

Thanks for starting this discussion @madebr!

**Pull request closed without merging**
