### PR TITLE
Add a check for a valid SPDX name + other improvements

### PR DESCRIPTION
**Pull request by Croydon**
Highlights: When working on a recipe you can just execute `bincrafters-conventions` and old stuff gets updated and additional checks are getting executed and warns you if something isn't right.
Not all good things do require to execute three commends in a row! 😁 

"Additional checks" are checks we can perform to ensure a higher recipe quality, but if the recipe doesn't pass the check there is nothing we can automatically do to improve it.

The first additional check is if the license attribute is a valid SPDX identifier as it should be according to Conan conventions.

Moreover:
  * when updating the travis file (`-t`) the renaming from .travis -> .ci happens now as well
  * adds `--check`  to only run additional checks 
  * provide default names for the options `-t`. `-a` and `-c`

### CODE REVIEW

**Comment by Croydon** [comment]
@uilianries Any idea why pytest wants to use Python 2? (see AppVeyor logs)

**Review by uilianries — APPROVED** [review]
LGTM

**Comment by uilianries** [comment]
Looks like pytest is forcing python2 on Windows :man_facepalming:

**Comment by uilianries** [comment]
@Croydon no idea why pytest is forcing python2.7, but could you try:

    python3 -m pytest -v --cov=bincrafters_conventions

**Comment by Croydon** [comment]
Ah, seems like PATH updating is enough 🎉

**Comment by uilianries** [comment]
Great! :clap:

**Pull request merged**
