### PR TITLE
use appveyor's virtualenv

### PR DESCRIPTION
**Pull request by ericLemanissier**

### CODE REVIEW

**Comment by Croydon** [comment]
I'm pretty sure there is a reason why I haven't used that before 🤔 

Does it only offer specific Python versions or is it completely new for the AppVeyor Linux images or something?

**Comment by ericLemanissier** [comment]
there is quite a lot of choice of versions on [linux](https://www.appveyor.com/docs/linux-images-software/#python) and [macos](https://www.appveyor.com/docs/macos-images-software/#python)
It's true that [windows](https://www.appveyor.com/docs/windows-images-software/#python) does not have virtualenv. Also, maybe you wanted to stay as much as possible independent of the CI service ? (you would still have to change some environment variable though)

**Comment by Croydon** [comment]
> Also, maybe you wanted to stay as much as possible independent of the CI service ?

Probably. The code right now is also similar to what we do on Travis for macOS

https://github.com/bincrafters/templates/blob/master/.ci/internal/travis-steps.yml#L11

I also made bad experience with pre-installed Python versions on the images for Azure Pipeline and GitHub Actions as they regular remove older versions and this break things

How much time do we save for a run by using AppVeyor's pre-installed Python?

**Comment by Croydon** [comment]
Comparing those two runs we save 3 minutes

https://ci.appveyor.com/project/ericLemanissier/conan-center-index/builds/35013977
https://ci.appveyor.com/project/ericLemanissier/conan-center-index/builds/35014505

This is certainly an argument. Specifically, when the bot is supposed to do even more in the future 😄

**Review by Croydon — APPROVED** [review]
LGTM

**Comment by ericLemanissier** [comment]
most of the 40 seconds left are spent in `pip install --quiet bincrafters-conventions`, but this one probably cannot be reduced

**Pull request merged**
